-- ============================================================
--  نظام إدارة عيادة التغذية — مخطط قاعدة البيانات (PostgreSQL)
--  يعمل كما هو على: Neon / Vercel Postgres / Supabase / أي Postgres ≥ 14 / PGlite محلياً
--  ملاحظة: الأعمدة المشتقة (BMI، المجاميع، الإيرادات) لا تُدخل
--  من العميل إطلاقاً؛ تُحسب في السيرفر = حماية للصيغ من العبث.
--  التواريخ نصوص بصيغة ISO (YYYY-MM-DD و YYYY-MM-DD HH:MM:SS بتوقيت UTC)
--  كي تبقى المقارنة والترتيب والتصدير بسيطة وثابتة عبر كل العملاء (ويب/موبايل).
--  هذا الملف يُطبَّق عند كل إقلاع ويجب أن يبقى آمناً للتكرار (IF NOT EXISTS).
-- ============================================================

-- ---------- المستخدمون والصلاحيات ----------
CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT    NOT NULL UNIQUE,
  password_hash TEXT    NOT NULL,
  full_name     TEXT    NOT NULL,
  role          TEXT    NOT NULL DEFAULT 'staff'   -- admin | staff | viewer
                CHECK (role IN ('admin','staff','viewer')),
  active        INTEGER NOT NULL DEFAULT 1,
  last_login_at TEXT,
  created_at    TEXT    NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

-- ---------- المرضى ----------
CREATE TABLE IF NOT EXISTS patients (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_no      TEXT    NOT NULL UNIQUE,              -- رقم الملف التلقائي (مثال NC-0001)
  first_name   TEXT    NOT NULL,
  last_name    TEXT    NOT NULL,
  phone        TEXT,
  birth_date   TEXT,                                  -- YYYY-MM-DD
  gender       TEXT    CHECK (gender IN ('male','female')),
  height_cm    DOUBLE PRECISION,
  start_weight DOUBLE PRECISION,                      -- وزن البداية (كيغرام)
  goal_weight  DOUBLE PRECISION,                      -- الوزن المستهدف
  goal         TEXT,                                  -- الهدف الغذائي (نص)
  notes        TEXT,
  status       TEXT    NOT NULL DEFAULT 'active'
               CHECK (status IN ('active','inactive','archived')),
  created_at   TEXT    NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  created_by   INTEGER REFERENCES users(id) ON DELETE SET NULL,
  updated_at   TEXT    NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_patients_name  ON patients(last_name, first_name);
CREATE INDEX IF NOT EXISTS idx_patients_phone ON patients(phone);

-- ---------- الزيارات ----------
CREATE TABLE IF NOT EXISTS visits (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id  INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  visit_date  TEXT    NOT NULL,                        -- YYYY-MM-DD
  visit_type  TEXT    NOT NULL DEFAULT 'followup'
              CHECK (visit_type IN ('initial','followup','consult','plan_update','lab_review')),
  reason      TEXT,
  created_by  INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at  TEXT    NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_visits_patient ON visits(patient_id, visit_date DESC);

-- ---------- القياسات / المتابعة ----------
CREATE TABLE IF NOT EXISTS measurements (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id    INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  visit_id      INTEGER REFERENCES visits(id) ON DELETE CASCADE,
  measured_on   TEXT    NOT NULL,                      -- YYYY-MM-DD
  weight_kg     DOUBLE PRECISION,
  height_cm     DOUBLE PRECISION,
  bmi           DOUBLE PRECISION,                      -- محسوب آلياً — للعرض فقط
  waist_cm      DOUBLE PRECISION,
  chest_cm      DOUBLE PRECISION,
  hip_cm        DOUBLE PRECISION,
  body_fat_pct  DOUBLE PRECISION,
  notes         TEXT,
  created_by    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at    TEXT    NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_meas_patient ON measurements(patient_id, measured_on);

-- ---------- البرامج الغذائية ----------
CREATE TABLE IF NOT EXISTS diet_plans (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id       INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  title            TEXT    NOT NULL,
  start_date       TEXT,
  end_date         TEXT,
  target_kcal      DOUBLE PRECISION,
  target_protein_g DOUBLE PRECISION,
  target_carbs_g   DOUBLE PRECISION,
  target_fat_g     DOUBLE PRECISION,
  advice           TEXT,
  status           TEXT    NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','archived')),
  created_by       INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at       TEXT    NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at       TEXT    NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_plans_patient ON diet_plans(patient_id, status);

-- ---------- وجبات البرنامج الغذائي ----------
CREATE TABLE IF NOT EXISTS diet_meals (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id    INTEGER NOT NULL REFERENCES diet_plans(id) ON DELETE CASCADE,
  slot       TEXT    NOT NULL,
  slot_time  TEXT,
  title      TEXT    NOT NULL,
  items      TEXT,
  portions   TEXT,
  kcal       DOUBLE PRECISION,
  protein_g  DOUBLE PRECISION,
  carbs_g    DOUBLE PRECISION,
  fat_g      DOUBLE PRECISION,
  position   INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_meals_plan ON diet_meals(plan_id, position);

-- ---------- المواعيد ----------
CREATE TABLE IF NOT EXISTS appointments (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id   INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  date         TEXT    NOT NULL,                       -- YYYY-MM-DD
  time         TEXT    NOT NULL,                       -- HH:MM
  duration_min INTEGER NOT NULL DEFAULT 30,
  visit_type   TEXT    NOT NULL DEFAULT 'followup'
               CHECK (visit_type IN ('initial','followup','consult','plan_update','lab_review')),
  status       TEXT    NOT NULL DEFAULT 'scheduled'
               CHECK (status IN ('scheduled','confirmed','done','cancelled','no_show')),
  room         TEXT,
  notes        TEXT,
  created_by   INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at   TEXT    NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_appt_date ON appointments(date, time);
CREATE UNIQUE INDEX IF NOT EXISTS uq_appt_slot ON appointments(date, time) WHERE status IN ('scheduled','confirmed');

-- ---------- المدفوعات ----------
CREATE TABLE IF NOT EXISTS payments (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id     INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  appointment_id INTEGER REFERENCES appointments(id) ON DELETE SET NULL,
  paid_on        TEXT    NOT NULL,                     -- YYYY-MM-DD
  service        TEXT    NOT NULL,
  amount         DOUBLE PRECISION NOT NULL CHECK (amount >= 0),
  currency       TEXT    NOT NULL DEFAULT 'SDG',
  method         TEXT    NOT NULL DEFAULT 'cash'
                 CHECK (method IN ('cash','card','bank_transfer','mobile_wallet','instalment')),
  invoice_no     TEXT,
  note           TEXT,
  voided         INTEGER NOT NULL DEFAULT 0,
  recorded_by    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at     TEXT    NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_pay_date ON payments(paid_on);
CREATE INDEX IF NOT EXISTS idx_pay_patient ON payments(patient_id);

-- ---------- سجل التدقيق (من عدّل ماذا ومتى) ----------
CREATE TABLE IF NOT EXISTS audit_log (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action     TEXT NOT NULL,
  entity     TEXT NOT NULL,
  entity_id  INTEGER,
  detail     TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_audit_time ON audit_log(created_at DESC);

-- ---------- إعدادات العيادة (المفاتيح التي تبدأ بـ _ داخلية ولا تُعرض) ----------
CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT
);

-- ---------- نسخ أمان تلقائية قبل كل استعادة (تبقى داخل القاعدة نفسها) ----------
CREATE TABLE IF NOT EXISTS backup_snapshots (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reason     TEXT NOT NULL,
  payload    TEXT NOT NULL,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

-- ============================================================
--  الإصدار 3: ميزات المتابعة الذكية (ترحيل آمن للتكرار على قواعد قائمة)
-- ============================================================
-- مستوى النشاط (لحساب السعرات) + الاشتراك في تذكيرات واتساب
ALTER TABLE patients ADD COLUMN IF NOT EXISTS activity_level TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS reminders_opt_in INTEGER NOT NULL DEFAULT 1;  -- تذكير المواعيد
ALTER TABLE patients ADD COLUMN IF NOT EXISTS daily_reminder   INTEGER NOT NULL DEFAULT 0;  -- تذكير يومي بالخطة
DO $$ BEGIN
  ALTER TABLE patients ADD CONSTRAINT chk_activity_level
    CHECK (activity_level IS NULL OR activity_level IN ('sedentary','light','moderate','active','very_active'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- تقييم الالتزام بالخطة في كل زيارة (0–100٪) + ملاحظة
ALTER TABLE visits ADD COLUMN IF NOT EXISTS adherence       INTEGER;
ALTER TABLE visits ADD COLUMN IF NOT EXISTS adherence_notes TEXT;
DO $$ BEGIN
  ALTER TABLE visits ADD CONSTRAINT chk_adherence CHECK (adherence IS NULL OR adherence BETWEEN 0 AND 100);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- الخطة الأسبوعية: يوم الوجبة (0=السبت … 6=الجمعة)، NULL = كل يوم
ALTER TABLE diet_meals ADD COLUMN IF NOT EXISTS day_of_week SMALLINT;
DO $$ BEGIN
  ALTER TABLE diet_meals ADD CONSTRAINT chk_day_of_week CHECK (day_of_week IS NULL OR day_of_week BETWEEN 0 AND 6);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- هل أُرسل تذكير هذا الموعد؟ (يمنع التكرار عند تشغيل المهمة اليومية أكثر من مرة)
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS reminded_at TEXT;

-- سجل رسائل واتساب (المرسلة آلياً أو يدوياً) — للتدقيق ومعرفة ما فشل
CREATE TABLE IF NOT EXISTS message_log (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id   INTEGER REFERENCES patients(id) ON DELETE SET NULL,
  channel      TEXT NOT NULL DEFAULT 'whatsapp',
  kind         TEXT NOT NULL,          -- appointment_reminder | daily_reminder | plan | shopping_list | custom | test
  to_phone     TEXT,
  body         TEXT,
  status       TEXT NOT NULL CHECK (status IN ('sent','failed','skipped','link')),
  provider_id  TEXT,
  error        TEXT,
  ref_id       INTEGER,                -- رقم الموعد/الخطة المرتبطة
  created_by   INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at   TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_msg_time ON message_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_msg_ref  ON message_log(kind, ref_id);

-- ================= الإصدار 4: بوابة المريض =================
-- رموز دخول المريض (QR + رمز احتياطي). يُخزَّن الـ hash فقط؛ إعادة الإصدار تلغي القديم.
CREATE TABLE IF NOT EXISTS patient_access (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id    INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  token_hash    TEXT NOT NULL UNIQUE,
  code_hash     TEXT NOT NULL,
  created_by    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at    TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  last_used_at  TEXT,
  use_count     INTEGER NOT NULL DEFAULT 0,
  revoked_at    TEXT
);
CREATE INDEX IF NOT EXISTS idx_access_patient ON patient_access(patient_id) WHERE revoked_at IS NULL;

-- متتبّع العادات اليومية (سجل واحد لكل مريض لكل يوم)
CREATE TABLE IF NOT EXISTS habit_logs (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id    INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  log_date      TEXT NOT NULL,                              -- YYYY-MM-DD بتوقيت العيادة
  water_ml      INTEGER CHECK (water_ml IS NULL OR water_ml BETWEEN 0 AND 10000),
  sleep_hours   DOUBLE PRECISION CHECK (sleep_hours IS NULL OR sleep_hours BETWEEN 0 AND 24),
  activity_min  INTEGER CHECK (activity_min IS NULL OR activity_min BETWEEN 0 AND 1440),
  activity_type TEXT,
  steps         INTEGER CHECK (steps IS NULL OR steps BETWEEN 0 AND 150000),
  note          TEXT,
  source        TEXT NOT NULL DEFAULT 'portal' CHECK (source IN ('portal','clinic')),
  created_at    TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at    TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (patient_id, log_date)
);
CREATE INDEX IF NOT EXISTS idx_habits_patient ON habit_logs(patient_id, log_date DESC);
ALTER TABLE patients ADD COLUMN IF NOT EXISTS water_target_ml     INTEGER;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS sleep_target_h      DOUBLE PRECISION;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS activity_target_min INTEGER;

-- نوع الموعد: حضوري أو استشارة فيديو
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS mode TEXT NOT NULL DEFAULT 'in_person';
DO $$ BEGIN
  ALTER TABLE appointments ADD CONSTRAINT chk_appt_mode CHECK (mode IN ('in_person','video'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- قائمة الانتظار الافتراضية
CREATE TABLE IF NOT EXISTS waitlist (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id     INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  status         TEXT NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting','booked','cancelled','expired')),
  date_from      TEXT,                                      -- نطاق التواريخ المقبول (اختياري)
  date_to        TEXT,
  days           TEXT,                                      -- أيام الأسبوع المقبولة "0,2,4" (0 = الأحد)
  time_pref      TEXT NOT NULL DEFAULT 'any' CHECK (time_pref IN ('any','morning','afternoon','evening')),
  visit_type     TEXT NOT NULL DEFAULT 'followup',
  mode           TEXT NOT NULL DEFAULT 'in_person',
  note           TEXT,
  source         TEXT NOT NULL DEFAULT 'portal' CHECK (source IN ('portal','clinic')),
  appointment_id INTEGER REFERENCES appointments(id) ON DELETE SET NULL,
  created_by     INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_waitlist_status ON waitlist(status, created_at);

-- عروض المواعيد الشاغرة لمرضى قائمة الانتظار (الأسبق للقبول يحجز)
CREATE TABLE IF NOT EXISTS waitlist_offers (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  waitlist_id    INTEGER NOT NULL REFERENCES waitlist(id) ON DELETE CASCADE,
  patient_id     INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  slot_date      TEXT NOT NULL,
  slot_time      TEXT NOT NULL,
  duration_min   INTEGER NOT NULL DEFAULT 30,
  source_appointment_id INTEGER,                            -- الموعد الملغى (بلا FK: قد يُحذف)
  status         TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','declined','expired','taken')),
  expires_at     TEXT NOT NULL,                             -- بتوقيت العيادة «YYYY-MM-DD HH:MM»
  notify_status  TEXT,                                      -- sent | link | failed | skipped
  appointment_id INTEGER REFERENCES appointments(id) ON DELETE SET NULL,
  created_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  responded_at   TEXT
);
CREATE INDEX IF NOT EXISTS idx_offers_slot ON waitlist_offers(slot_date, slot_time, status);
CREATE INDEX IF NOT EXISTS idx_offers_patient ON waitlist_offers(patient_id, status);

-- الاستشارات المرئية: جلسة + إشارات WebRTC (SDP) عبر الاستطلاع — لا WebSocket على Vercel
CREATE TABLE IF NOT EXISTS call_sessions (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id    INTEGER REFERENCES appointments(id) ON DELETE CASCADE,
  patient_id        INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  status            TEXT NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting','active','ended')),
  started_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  connected_at      TEXT,
  ended_at          TEXT,
  doctor_seen_at    TEXT,
  patient_seen_at   TEXT
);
CREATE INDEX IF NOT EXISTS idx_calls_patient ON call_sessions(patient_id, status);
CREATE TABLE IF NOT EXISTS call_signals (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id     INTEGER NOT NULL REFERENCES call_sessions(id) ON DELETE CASCADE,
  sender      TEXT NOT NULL CHECK (sender IN ('doctor','patient')),
  kind        TEXT NOT NULL CHECK (kind IN ('hello','offer','answer','ice','bye','state')),
  payload     TEXT,
  created_at  TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_signals_call ON call_signals(call_id, id);

-- ---------- منظر: الملف المالي لكل مريض ----------
CREATE OR REPLACE VIEW patient_financials AS
SELECT p.id AS patient_id,
       COALESCE(SUM(CASE WHEN pa.voided = 0 THEN pa.amount ELSE 0 END), 0) AS paid_total,
       COUNT(pa.id)                                                        AS payments_count
FROM patients p
LEFT JOIN payments pa ON pa.patient_id = p.id
GROUP BY p.id;

-- المرحلة E: التاريخ الطبي المنظّم (مستوحى من نسخة AI Studio)
ALTER TABLE patients ADD COLUMN IF NOT EXISTS chronic_conditions TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS allergies          TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS medications        TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS forbidden_foods    TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS blood_type         TEXT;

-- المرحلة E: الألياف والماء في البرنامج الغذائي
ALTER TABLE diet_plans ADD COLUMN IF NOT EXISTS target_fiber_g  DOUBLE PRECISION;
ALTER TABLE diet_plans ADD COLUMN IF NOT EXISTS target_water_ml INTEGER;
ALTER TABLE diet_meals ADD COLUMN IF NOT EXISTS fiber_g         DOUBLE PRECISION;
